In [1]:
import numpy as np
import pandas as pd
from pandas import Series,DataFrame

In [12]:
imdb = pd.read_csv('data/movie_metadata.csv')

In [14]:
imdb.shape

(5043, 28)

In [16]:
imdb.head()

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0

In [17]:
imdb.tail()

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
5038,Color,Scott Smith,1.0,87.0,2.0,318.0,Daphne Zuniga,637.0,NaN,Comedy|Drama,...,6.0,English,Canada,NaN,NaN,2013.0,470.0,7.7,NaN,84
5039,Color,NaN,43.0,43.0,NaN,319.0,Valorie Curry,841.0,NaN,Crime|Drama|Mystery|Thriller,...,359.0,English,USA,TV-14,NaN,NaN,593.0,7.5,16.00,32000
5040,Color,Benjamin Roberds,13.0,76.0,0.0,0.0,Maxwell Moody,0.0,NaN,Drama|Horror|Thriller,...,3.0,English,USA,NaN,1400.0,2013.0,0.0,6.3,NaN,16
5041,Color,Daniel Hsia,14.0,100.0,0.0,489.0,Daniel Henney,946.0,10443.0,Comedy|Drama|Romance,...,9.0,English,USA,PG-13,NaN,2012.0,719.0,6.3,2.35,660
5042,Color,Jon Gunn,43.0,90.0,16.0,16.0,Brian Herzlinger,86.0,85222.0,Documentary,...,84.0,English,USA,PG,1100.0,2004.0,23.0,6.6,1.85,456

In [18]:
imdb.head(10)

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0
5,Color,Andrew Stanton,462.0,132.0,475.0,530.0,Samantha Morton,640.0,73058679.0,Action|Adventure|Sci-Fi,...,738.0,English,USA,PG-13,263700000.0,2012.0,632.0,6.6,2.35,24000
6,Color,Sam Raimi,392.0,156.0,0.0,4000.0,James Franco,24000.0,336530303.0,Action|Adventure|Romance,...,1902.0,English,USA,PG-13,258000000.0,2007.0,11000.0,6.2,2.35,0
7,Color,Nathan Greno,324.0,100.0,15.0,284.0,Donna Murphy,799.0,200807262.0,Adventure|Animation|Comedy|Family|Fantasy|Musi...,...,387.0,English,USA,PG,260000000.0,2010.0,553.0,7.8,1.85,29000
8,Color,Joss Whedon,635.0,141.0,0.0,19000.0,Robert Downey Jr.,26000.0,458991599.0,Action|Adventure|Sci-Fi,...,1117.0,English,USA,PG-13,250000000.0,2015.0,21000.0,7.5,2.35,118000
9,Color,David Yates,375.0,153.0,282.0,10000.0,Daniel Radcliffe,25000.0,301956980.0,Adventure|Family|Fantasy|Mystery,...,973.0,English,UK,PG,250000000.0,2009.0,11000.0,7.5,2.35,10000

In [20]:
imdb[['color','director_name']]

                 color       director_name
0                Color       James Cameron
1                Color      Gore Verbinski
2                Color          Sam Mendes
3                Color   Christopher Nolan
4                  NaN         Doug Walker
5                Color      Andrew Stanton
6                Color           Sam Raimi
7                Color        Nathan Greno
8                Color         Joss Whedon
9                Color         David Yates
10               Color         Zack Snyder
11               Color        Bryan Singer
12               Color        Marc Forster
13               Color      Gore Verbinski
14               Color      Gore Verbinski
15               Color         Zack Snyder
16               Color      Andrew Adamson
17               Color         Joss Whedon
18               Color        Rob Marshall
19               Color    Barry Sonnenfeld
20               Color       Peter Jackson
21               Color           Marc Webb
22               Color        Ridley Scott
23               Color       Peter Jackson
24               Color         Chris Weitz
25               Color       Peter Jackson
26               Color       James Cameron
27               Color       Anthony Russo
28               Color          Peter Berg
29               Color     Colin Trevorrow
...                ...                 ...
5013             Color          Eric Eason
5014             Color            Uwe Boll
5015   Black and White   Richard Linklater
5016             Color     Joseph Mazzella
5017             Color        Travis Legge
5018             Color       Alex Kendrick
5019             Color       Marcus Nispel
5020               NaN     Brandon Landers
5021             Color         Jay Duplass
5022   Black and White          Jim Chuchu
5023             Color          Daryl Wein
5024             Color         Jason Trost
5025             Color         John Waters
5026             Color     Olivier Assayas
5027             Color        Jafar Panahi
5028   Black and White       Ivan Kavanagh
5029             Color    Kiyoshi Kurosawa
5030             Color        Tadeo Garcia
5031             Color  Thomas L. Phillips
5032             Color     Ash Baron-Cohen
5033             Color       Shane Carruth
5034             Color    Neill Dela Llana
5035             Color    Robert Rodriguez
5036             Color     Anthony Vallone
5037             Color        Edward Burns
5038             Color         Scott Smith
5039             Color                 NaN
5040             Color    Benjamin Roberds
5041             Color         Daniel Hsia
5042             Color            Jon Gunn

[5043 rows x 2 columns]

In [39]:
imdb.loc[1:20, :]

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0
5,Color,Andrew Stanton,462.0,132.0,475.0,530.0,Samantha Morton,640.0,73058679.0,Action|Adventure|Sci-Fi,...,738.0,English,USA,PG-13,263700000.0,2012.0,632.0,6.6,2.35,24000
6,Color,Sam Raimi,392.0,156.0,0.0,4000.0,James Franco,24000.0,336530303.0,Action|Adventure|Romance,...,1902.0,English,USA,PG-13,258000000.0,2007.0,11000.0,6.2,2.35,0
7,Color,Nathan Greno,324.0,100.0,15.0,284.0,Donna Murphy,799.0,200807262.0,Adventure|Animation|Comedy|Family|Fantasy|Musi...,...,387.0,English,USA,PG,260000000.0,2010.0,553.0,7.8,1.85,29000
8,Color,Joss Whedon,635.0,141.0,0.0,19000.0,Robert Downey Jr.,26000.0,458991599.0,Action|Adventure|Sci-Fi,...,1117.0,English,USA,PG-13,250000000.0,2015.0,21000.0,7.5,2.35,118000
9,Color,David Yates,375.0,153.0,282.0,10000.0,Daniel Radcliffe,25000.0,301956980.0,Adventure|Family|Fantasy|Mystery,...,973.0,English,UK,PG,250000000.0,2009.0,11000.0,7.5,2.35,10000
10,Color,Zack Snyder,673.0,183.0,0.0,2000.0,Lauren Cohan,15000.0,330249062.0,Action|Adventure|Sci-Fi,...,3018.0,English,USA,PG-13,250000000.0,2016.0,4000.0,6.9,2.35,197000
11,Color,Bryan Singer,434.0,169.0,0.0,903.0,Marlon Brando,18000.0,200069408.0,Action|Adventure|Sci-Fi,...,2367.0,English,USA,PG-13,209000000.0,2006.0,10000.0,6.1,2.35,0
12,Color,Marc Forster,403.0,106.0,395.0,393.0,Mathieu Amalric,451.0,168368427.0,Action|Adventure,...,1243.0,English,UK,PG-13,200000000.0,2008.0,412.0,6.7,2.35,0
13,Color,Gore Verbinski,313.0,151.0,563.0,1000.0,Orlando Bloom,40000.0,423032628.0,Action|Adventure|Fantasy,...,1832.0,English,USA,PG-13,225000000.0,2006.0,5000.0,7.3,2.35,5000
14,Color,Gore Verbinski,450.0,150.0,563.0,1000.0,Ruth Wilson,40000.0,89289910.0,Action|Adventure|Western,...,711.0,English,USA,PG-13,215000000.0,2013.0,2000.0,6.5,2.35,48000
15,Color,Zack Snyder,733.0,143.0,0.0,748.0,Christopher Meloni,15000.0,291021565.0,Action|Adventure|Fantasy|Sci-Fi,...,2536.0,English,USA,PG-13,225000000.0,2013.0,3000.0,7.2,2.35,118000
16,Color,Andrew Adamson,258.0,150.0,80.0,201.0,Pierfrancesco Favino,22000.0,141614023.0,Action|Adventure|Family|Fantasy,...,438.0,English,USA,PG,225000000.0,2008.0,216.0,6.6,2.35,0
17,Color,Joss Whedon,703.0,173.0,0.0,19000.0,Robert Downey Jr.,26000.0,623279547.0,Action|Adventure|Sci-Fi,...,1722.0,English,USA,PG-13,220000000.0,2012.0,21000.0,8.1,1.85,123000
18,Color,Rob Marshall,448.0,136.0,252.0,1000.0,Sam Claflin,40000.0,241063875.0,Action|Adventure|Fantasy,...,484.0,English,USA,PG-13,250000000.0,2011.0,11000.0,6.7,2.35,58000
19,Color,Barry Sonnenfeld,451.0,106.0,188.0,718.0,Michael Stuhlbarg,10000.0,179020854.0,Action|Adventure|Comedy|Family|Fantasy|Sci-Fi,...,341.0,English,USA,PG-13,225000000.0,2012.0,816.0,6.8,1.85,40000
20,Color,Peter Jackson,422.0,164.0,0.0,773.0,Adam Brown,5000.0,255108370.0,Adventure|Fantasy,...,802.0,English,New Zealand,PG-13,250000000.0,2014.0,972.0,7.5,2.35,65000

In [21]:
sub_df = imdb[['director_name','movie_title','imdb_score']]

In [22]:
sub_df.head(5)  # head doesnt support slice

,director_name,movie_title,imdb_score
0,James Cameron,Avatar,7.9
1,Gore Verbinski,Pirates of the Caribbean: At World's End,7.1
2,Sam Mendes,Spectre,6.8
3,Christopher Nolan,The Dark Knight Rises,8.5
4,Doug Walker,Star Wars: Episode VII - The Force AwakensÂ ...,7.1

In [24]:
sub_df.iloc[10:20, 0:2]  # 10-19, 0-1   based on index(position)

       director_name                                   movie_title
10       Zack Snyder           Batman v Superman: Dawn of JusticeÂ
11      Bryan Singer                             Superman ReturnsÂ
12      Marc Forster                            Quantum of SolaceÂ
13    Gore Verbinski   Pirates of the Caribbean: Dead Man's ChestÂ
14    Gore Verbinski                              The Lone RangerÂ
15       Zack Snyder                                 Man of SteelÂ
16    Andrew Adamson     The Chronicles of Narnia: Prince CaspianÂ
17       Joss Whedon                                 The AvengersÂ
18      Rob Marshall  Pirates of the Caribbean: On Stranger TidesÂ
19  Barry Sonnenfeld                               Men in Black 3Â

In [25]:
sub_df.iloc[10:20, :]

       director_name                                   movie_title  imdb_score
10       Zack Snyder           Batman v Superman: Dawn of JusticeÂ          6.9
11      Bryan Singer                             Superman ReturnsÂ          6.1
12      Marc Forster                            Quantum of SolaceÂ          6.7
13    Gore Verbinski   Pirates of the Caribbean: Dead Man's ChestÂ          7.3
14    Gore Verbinski                              The Lone RangerÂ          6.5
15       Zack Snyder                                 Man of SteelÂ          7.2
16    Andrew Adamson     The Chronicles of Narnia: Prince CaspianÂ          6.6
17       Joss Whedon                                 The AvengersÂ          8.1
18      Rob Marshall  Pirates of the Caribbean: On Stranger TidesÂ          6.7
19  Barry Sonnenfeld                               Men in Black 3Â          6.8

In [26]:
tmp_df = sub_df.iloc[10:20,0:2]
tmp_df.iloc[2:4, :]

     director_name                                  movie_title
12    Marc Forster                           Quantum of SolaceÂ
13  Gore Verbinski  Pirates of the Caribbean: Dead Man's ChestÂ

In [28]:
tmp_df

       director_name                                   movie_title
10       Zack Snyder           Batman v Superman: Dawn of JusticeÂ
11      Bryan Singer                             Superman ReturnsÂ
12      Marc Forster                            Quantum of SolaceÂ
13    Gore Verbinski   Pirates of the Caribbean: Dead Man's ChestÂ
14    Gore Verbinski                              The Lone RangerÂ
15       Zack Snyder                                 Man of SteelÂ
16    Andrew Adamson     The Chronicles of Narnia: Prince CaspianÂ
17       Joss Whedon                                 The AvengersÂ
18      Rob Marshall  Pirates of the Caribbean: On Stranger TidesÂ
19  Barry Sonnenfeld                               Men in Black 3Â

In [31]:
tmp_df.loc[15:17,:]  # 15-17  loc is lable not index

     director_name                                movie_title
15     Zack Snyder                              Man of SteelÂ
16  Andrew Adamson  The Chronicles of Narnia: Prince CaspianÂ
17     Joss Whedon                              The AvengersÂ

In [34]:
tmp_df.loc[15:17,'movie_title':'movie_title']  # from  xx to movie_title

                                  movie_title
15                              Man of SteelÂ
16  The Chronicles of Narnia: Prince CaspianÂ
17                              The AvengersÂ