In [12]:
import tushare

In [14]:
import tushare as ts

ts.get_hist_data('600848') #一次性获取全部日k线数据

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>open</th>
      <th>high</th>
      <th>close</th>
      <th>low</th>
      <th>volume</th>
      <th>price_change</th>
      <th>p_change</th>
      <th>ma5</th>
      <th>ma10</th>
      <th>ma20</th>
      <th>v_ma5</th>
      <th>v_ma10</th>
      <th>v_ma20</th>
    </tr>
    <tr>
      <th>date</th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>2020-04-14</th>
      <td>19.20</td>
      <td>19.36</td>
      <td>19.35</td>
      <td>19.12</td>
      <td>24102.21</td>
      <td>0.24</td>
      <td>1.26</td>
      <td>19.418</td>
      <td>19.559</td>
      <td>19.339</td>
      <td>27476.99</td>
      <td>42044.24</td>
      <td>44088.32</td>
    </tr>
    <tr>
      <th>2020-04-13</th>
      <td>19.48</td>
      <td>19.48</td>
      <td>19.11</td>
      <td>19.01</td>
      <td>23232.98</td>
      <td>-0.40</td>
      <td>-2.05</td>
      <td>19.500</td>
      <td>19.584</td>
      <td>19.361</td>
      <td>29939.95</td>
      <td>48381.43</td>
      <td>46148.55</td>
    </tr>
    <tr>
      <th>2020-04-10</th>
      <td>19.63</td>
      <td>19.79</td>
      <td>19.51</td>
      <td>19.44</td>
      <td>34893.70</td>
      <td>-0.06</td>
      <td>-0.31</td>
      <td>19.588</td>
      <td>19.558</td>
      <td>19.415</td>
      <td>31500.69</td>
      <td>49040.12</td>
      <td>48605.40</td>
    </tr>
    <tr>
      <th>2020-04-09</th>
      <td>19.65</td>
      <td>19.74</td>
      <td>19.57</td>
      <td>19.50</td>
      <td>24648.34</td>
      <td>0.02</td>
      <td>0.10</td>
      <td>19.606</td>
      <td>19.498</td>
      <td>19.472</td>
      <td>32189.58</td>
      <td>49019.91</td>
      <td>49266.38</td>
    </tr>
    <tr>
      <th>2020-04-08</th>
      <td>19.76</td>
      <td>19.79</td>
      <td>19.55</td>
      <td>19.49</td>
      <td>30507.70</td>
      <td>-0.21</td>
      <td>-1.06</td>
      <td>19.590</td>
      <td>19.464</td>
      <td>19.545</td>
      <td>39679.58</td>
      <td>51809.92</td>
      <td>51369.69</td>
    </tr>
    <tr>
      <th>...</th>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
    </tr>
    <tr>
      <th>2017-10-20</th>
      <td>29.20</td>
      <td>29.83</td>
      <td>28.33</td>
      <td>27.85</td>
      <td>411570.12</td>
      <td>1.17</td>
      <td>4.31</td>
      <td>26.360</td>
      <td>26.360</td>
      <td>26.360</td>
      <td>176454.41</td>
      <td>176454.41</td>
      <td>176454.41</td>
    </tr>
    <tr>
      <th>2017-10-19</th>
      <td>25.61</td>
      <td>27.20</td>
      <td>27.16</td>
      <td>25.61</td>
      <td>180490.47</td>
      <td>1.47</td>
      <td>5.72</td>
      <td>25.868</td>
      <td>25.868</td>
      <td>25.868</td>
      <td>117675.48</td>
      <td>117675.48</td>
      <td>117675.48</td>
    </tr>
    <tr>
      <th>2017-10-18</th>
      <td>25.63</td>
      <td>26.41</td>
      <td>25.69</td>
      <td>25.50</td>
      <td>109353.35</td>
      <td>0.26</td>
      <td>1.02</td>
      <td>25.437</td>
      <td>25.437</td>
      <td>25.437</td>
      <td>96737.15</td>
      <td>96737.15</td>
      <td>96737.15</td>
    </tr>
    <tr>
      <th>2017-10-17</th>
      <td>25.30</td>
      <td>25.88</td>
      <td>25.43</td>
      <td>25.23</td>
      <td>67649.41</td>
      <td>0.24</td>
      <td>0.95</td>
      <td>25.310</td>
      <td>25.310</td>
      <td>25.310</td>
      <td>90429.05</td>
      <td>90429.05</td>
      <td>90429.05</td>
    </tr>
    <tr>
      <th>2017-10-16</th>
      <td>26.40</td>
      <td>26.48</td>
      <td>25.19</td>
      <td>25.03</td>
      <td>113208.69</td>
      <td>-1.16</td>
      <td>-4.40</td>
      <td>25.190</td>
      <td>25.190</td>
      <td>25.190</td>
      <td>113208.69</td>
      <td>113208.69</td>
      <td>113208.69</td>
    </tr>
  </tbody>
</table>
<p>532 rows × 13 columns</p>
</div>

In [17]:
ts.get_hist_data('600848',start='2020-04-01',end='2020-04-14')

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>open</th>
      <th>high</th>
      <th>close</th>
      <th>low</th>
      <th>volume</th>
      <th>price_change</th>
      <th>p_change</th>
      <th>ma5</th>
      <th>ma10</th>
      <th>ma20</th>
      <th>v_ma5</th>
      <th>v_ma10</th>
      <th>v_ma20</th>
    </tr>
    <tr>
      <th>date</th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>2020-04-14</th>
      <td>19.20</td>
      <td>19.36</td>
      <td>19.35</td>
      <td>19.12</td>
      <td>24102.21</td>
      <td>0.24</td>
      <td>1.26</td>
      <td>19.418</td>
      <td>19.559</td>
      <td>19.339</td>
      <td>27476.99</td>
      <td>42044.24</td>
      <td>44088.32</td>
    </tr>
    <tr>
      <th>2020-04-13</th>
      <td>19.48</td>
      <td>19.48</td>
      <td>19.11</td>
      <td>19.01</td>
      <td>23232.98</td>
      <td>-0.40</td>
      <td>-2.05</td>
      <td>19.500</td>
      <td>19.584</td>
      <td>19.361</td>
      <td>29939.95</td>
      <td>48381.43</td>
      <td>46148.55</td>
    </tr>
    <tr>
      <th>2020-04-10</th>
      <td>19.63</td>
      <td>19.79</td>
      <td>19.51</td>
      <td>19.44</td>
      <td>34893.70</td>
      <td>-0.06</td>
      <td>-0.31</td>
      <td>19.588</td>
      <td>19.558</td>
      <td>19.415</td>
      <td>31500.69</td>
      <td>49040.12</td>
      <td>48605.40</td>
    </tr>
    <tr>
      <th>2020-04-09</th>
      <td>19.65</td>
      <td>19.74</td>
      <td>19.57</td>
      <td>19.50</td>
      <td>24648.34</td>
      <td>0.02</td>
      <td>0.10</td>
      <td>19.606</td>
      <td>19.498</td>
      <td>19.472</td>
      <td>32189.58</td>
      <td>49019.91</td>
      <td>49266.38</td>
    </tr>
    <tr>
      <th>2020-04-08</th>
      <td>19.76</td>
      <td>19.79</td>
      <td>19.55</td>
      <td>19.49</td>
      <td>30507.70</td>
      <td>-0.21</td>
      <td>-1.06</td>
      <td>19.590</td>
      <td>19.464</td>
      <td>19.545</td>
      <td>39679.58</td>
      <td>51809.92</td>
      <td>51369.69</td>
    </tr>
    <tr>
      <th>2020-04-07</th>
      <td>19.81</td>
      <td>19.90</td>
      <td>19.76</td>
      <td>19.66</td>
      <td>36417.02</td>
      <td>0.21</td>
      <td>1.07</td>
      <td>19.700</td>
      <td>19.399</td>
      <td>19.612</td>
      <td>56611.50</td>
      <td>52220.99</td>
      <td>53233.79</td>
    </tr>
    <tr>
      <th>2020-04-03</th>
      <td>19.60</td>
      <td>19.66</td>
      <td>19.55</td>
      <td>19.38</td>
      <td>31036.70</td>
      <td>-0.05</td>
      <td>-0.26</td>
      <td>19.668</td>
      <td>19.288</td>
      <td>19.665</td>
      <td>66822.90</td>
      <td>51644.05</td>
      <td>54915.32</td>
    </tr>
    <tr>
      <th>2020-04-02</th>
      <td>19.35</td>
      <td>19.68</td>
      <td>19.60</td>
      <td>19.20</td>
      <td>38338.12</td>
      <td>0.11</td>
      <td>0.56</td>
      <td>19.528</td>
      <td>19.257</td>
      <td>19.760</td>
      <td>66579.54</td>
      <td>51502.34</td>
      <td>55608.34</td>
    </tr>
    <tr>
      <th>2020-04-01</th>
      <td>19.79</td>
      <td>20.25</td>
      <td>19.49</td>
      <td>19.46</td>
      <td>62098.35</td>
      <td>-0.61</td>
      <td>-3.04</td>
      <td>19.390</td>
      <td>19.217</td>
      <td>19.862</td>
      <td>65850.24</td>
      <td>53820.17</td>
      <td>56847.12</td>
    </tr>
  </tbody>
</table>
</div>